### ISSUE TITLE
JetBrains RustRover IDE lsp terminated

### ISSUE THREAD

**Issue by rootfebri** [kizeevov/slint-idea-plugin#55]
I don't know how to fix it
already did reinstalling IDE/Plugin (manual, marketplace)
my pc, please help

OS: Ubuntu 23.10 x86_64
Kernel: 6.5.0-35-generic

below is log when start rustrover from terminal, i don't know might be helping or not
> ➜  ~ rustrover
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
2024-05-26 16:02:55,905 [   1053]   WARN - #c.i.u.x.Binding - No accessors for com.mallowigi.idea.themes.MTThemeFacade. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-05-26 16:02:55,975 [   1123]   WARN - #c.i.i.u.UIThemeBean - Do not set theme id in JSON (value=f92a0fa7-1a98-47cd-b5cb-78ff67e6f4f3)
2024-05-26 16:02:55,986 [   1134]   WARN - #c.i.i.u.UIThemeBean - Do not set theme id in JSON (value=1a92aa6f-c2f1-4994-ae01-6a78e43eeb24)
2024-05-26 16:02:55,996 [   1144]   WARN - #c.i.i.u.UIThemeBean - Do not set theme id in JSON (value=4b6007f7-b596-4ee2-96f9-968d3d3eb392)
2024-05-26 16:02:56,006 [   1154]   WARN - #c.i.i.u.UIThemeBean - Do not set theme id in JSON (value=4f556d32-83cb-4b8b-9932-c4eccc4ce3af)
2024-05-26 16:02:56,230 [   1378]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Skipping '_@user_Gerry Violet' because its parent scheme 'Gerry Violet' is missing.
2024-05-26 16:02:56,231 [   1379]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Skipping '_@user_Gerry Storm' because its parent scheme 'Gerry Storm' is missing.
2024-05-26 16:02:56,231 [   1379]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Skipping '_@user_Gerry Oceanic' because its parent scheme 'Gerry Oceanic' is missing.
2024-05-26 16:02:56,232 [   1380]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Skipping '_@user_Gerry Dark' because its parent scheme 'Gerry Dark' is missing.
2024-05-26 16:02:56,232 [   1380]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Skipping '_@user_Gerry Darcula' because its parent scheme 'Gerry Darcula' is missing.
2024-05-26 16:02:56,768 [   1916]   WARN - #c.i.u.x.Binding - No accessors for java.awt.Color. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-05-26 16:02:57,082 [   2230]   WARN - #c.i.s.ComponentManagerImpl - com.github.copilot.platform.state.ToolWindowRegistrationSettings <clinit> requests com.github.copilot.platform.state.ToolWindowRegistrationSettings instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
2024-05-26 16:02:58,641 [   3789]   WARN - #c.i.p.l.i.LspServerImpl - SlintLspServerDescriptor@azblob(Initializing;0): Failed to start LSP server
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "null": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:367)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.platform.lsp.api.LspServerDescriptor$startServerProcess$1.<init>(LspServerDescriptor.kt:98)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:98)
	at dev.slint.ideaplugin.ide.lsp.SlintLspServerDescriptor.startServerProcess(SlintLspServerDescriptor.kt:28)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:17)
	at com.intellij.platform.lsp.impl.LspServerImpl.j(LspServerImpl.kt:318)
	at com.intellij.platform.lsp.impl.LspServerImpl.j(LspServerImpl.kt:298)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Cannot run program "null": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:491)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:464)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:357)
	... 18 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 22 more
false
false
2024-05-26 16:02:59,374 [   4522]   WARN - #c.i.u.x.Binding - No accessors for java.time.ZonedDateTime. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
false
false
false
SLF4J: A SLF4J service provider failed to instantiate:
org.slf4j.spi.SLF4JServiceProvider: org.slf4j.jul.JULServiceProvider not a subtype
[DefaultDispatcher-worker-24] INFO jetbrains.exodus.io.FileDataWriter - Uninterruptible file channel will be used
[DefaultDispatcher-worker-24] INFO jetbrains.exodus.env.EnvironmentImpl - Exodus environment created: /home/febri/.config/github-copilot/rr/chat-sessions/2gwXM5r7jbLI1wKSoG3zvETDYSz
^C2024-05-26 16:04:03,210 [  68358]   WARN - #c.i.o.v.i.l.NativeFileWatcherImpl - Watcher terminated with exit code 130

![Screenshot from 2024-05-27 01-02-30](https://github.com/kizeevov/slint-idea-plugin/assets/28066525/cdd6b41f-9bbf-4f62-8de7-169dbf11ab19)

**Comment by kizeevov** [comment]
It seems that it was not possible to determine the type of your operating system.
Workaround: 
1. [manually install slint-lsp](https://github.com/slint-ui/slint/tree/master/tools/lsp#generic-usage) 
```shell
cargo install slint-lsp
```
2. Select "Use external LSP server" in the settings and specify the path to the lsp server
<img width="987" alt="image" src="https://github.com/kizeevov/slint-idea-plugin/assets/29508723/9bf79162-3b6e-451f-a7d7-6d0538f5ddca">
