### ISSUE TITLE
PyCharm 2024.2 error message

### ISSUE THREAD

**Issue by Ss789** [kizeevov/slint-idea-plugin#61]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.slint.ideaplugin.ide.actions.PreviewAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.slint.ideaplugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by DASPRiD** [comment]
Same on all other 2024.2.x products, e.g. RustRover.

**Comment by kizeevov** [comment]
Fixed in version 1.3.0. Please check. 
Sorry for the long wait 😬

**Comment by kizeevov** [comment]
I'm closing it. The exception has been fixed. 
If there is a problem, please open a new issue.
